version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - echo HELLO_WORLD_1
            - npm ci --cache .npm --prefer-offline --legacy-peer-deps
        build:
          commands:
            # - REACT_APP_CAPTCHA=${REACT_APP_CAPTCHA}
            # - REACT_APP_EMAIL_SERVICE=${REACT_APP_EMAIL_SERVICE}
            # - REACT_APP_EMAIL_TEMPLATE=${REACT_APP_EMAIL_TEMPLATE}
            # - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}
            - echo HELLO_WORLD_2
            - npm run build
      artifacts:
        baseDirectory: dist
        files:
          - "**/*"
      cache:
        paths:
          - .npm/**/*
    appRoot: ZalaFrontend
